- id: issue_number_prepend
  name: issue_number_prepend
  description: "Prepend issue number to commit message"
  entry: ./commit_msg_issue_number_prepend.sh
  language: script
  args: []
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"
  stages:
    - commit-msg
- id: unstage_vscode_pytest_changes
  name: unstage_vscode_pytest_changes
  description: "Unstage vscode and pytest changes"
  entry: ./unstage_vscode_pytest_changes.sh
  language: script
  args: []
  require_serial: true
  stages:
    - pre-commit
